From isla Require Import isla_lang.

Definition a7424 : list trc := [
  [
    Smt (DeclareConst 3%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 5%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 6%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 10%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 12%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 13%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 17%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 18%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 21%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 26%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 27%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 28%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (Assert (Binop (Eq) (Val (Val_Bits [BV{64%N} 0x0%Z]) Mk_annot) (Val (Val_Bits [BV{64%N} 0x0%Z]) Mk_annot) Mk_annot)) Mk_annot;
    Smt (DeclareConst 42%Z (Ty_BitVec 64%N)) Mk_annot;
    ReadReg "_PC" [] (Val_Symbolic 42%Z) Mk_annot;
    Smt (DefineConst 43%Z (Manyop (Bvmanyarith Bvadd) [Val (Val_Symbolic 42%Z) Mk_annot; Val (Val_Bits [BV{64%N} 0x3d4%Z]) Mk_annot] Mk_annot)) Mk_annot;
    ReadReg "PSTATE" [Field "EL"] (Val_Struct [("EL", Val_Bits [BV{2%N} 0x2%Z])]) Mk_annot;
    ReadReg "SCTLR_EL2" [] (Val_Bits [BV{64%N} 0x4000002%Z]) Mk_annot;
    Smt (DefineConst 74%Z (Unop (Not) (Binop (Eq) (Val (Val_Symbolic 43%Z) Mk_annot) (Manyop (Bvmanyarith Bvand) [Val (Val_Symbolic 43%Z) Mk_annot; Val (Val_Bits [BV{64%N} 0xfffffffffffffff8%Z]) Mk_annot] Mk_annot) Mk_annot) Mk_annot)) Mk_annot;
    Branch 0%Z "model/aarch64.sail 13242:4 - 13245:5" Mk_annot;
    Smt (Assert (Val (Val_Symbolic 74%Z) Mk_annot)) Mk_annot;
    Smt (DeclareConst 79%Z Ty_Bool) Mk_annot;
    ReadReg "CFG_ID_AA64PFR0_EL1_EL3" [] (Val_Bits [BV{4%N} 0x1%Z]) Mk_annot;
    ReadReg "SCR_EL3" [] (Val_Bits [BV{32%N} 0x0%Z]) Mk_annot;
    ReadReg "CFG_ID_AA64PFR0_EL1_EL2" [] (Val_Bits [BV{4%N} 0x1%Z]) Mk_annot;
    ReadReg "PSTATE" [Field "nRW"] (Val_Struct [("nRW", Val_Symbolic 28%Z)]) Mk_annot;
    Smt (DefineConst 111%Z (Binop (Eq) (Val (Val_Symbolic 28%Z) Mk_annot) (Val (Val_Bits [BV{1%N} 0x1%Z]) Mk_annot) Mk_annot)) Mk_annot;
    ReadReg "CFG_ID_AA64PFR0_EL1_EL0" [] (Val_Bits [BV{4%N} 0x1%Z]) Mk_annot;
    ReadReg "CFG_ID_AA64PFR0_EL1_EL1" [] (Val_Bits [BV{4%N} 0x1%Z]) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 111%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 111%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (DefineConst 114%Z (Binop (Eq) (Val (Val_Symbolic 28%Z) Mk_annot) (Val (Val_Bits [BV{1%N} 0x1%Z]) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 114%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 114%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (DefineConst 117%Z (Val (Val_Symbolic 42%Z) Mk_annot)) Mk_annot;
    Branch 1%Z "model/aarch_mem.sail 6794:41 - 6794:77" Mk_annot;
    Smt (Assert (Val (Val_Symbolic 79%Z) Mk_annot)) Mk_annot;
    Smt (DefineConst 191%Z (Val (Val_Symbolic 43%Z) Mk_annot)) Mk_annot;
    Smt (Assert (Val (Val_Symbolic 79%Z) Mk_annot)) Mk_annot;
    Smt (DefineConst 204%Z (Binop (Eq) (Val (Val_Symbolic 28%Z) Mk_annot) (Val (Val_Bits [BV{1%N} 0x1%Z]) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 204%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 204%Z) Mk_annot) Mk_annot)) Mk_annot;
    ReadReg "PSTATE" [Field "SP"] (Val_Struct [("SP", Val_Bits [BV{1%N} 0x1%Z])]) Mk_annot;
    ReadReg "PSTATE" [Field "N"] (Val_Struct [("N", Val_Symbolic 17%Z)]) Mk_annot;
    ReadReg "PSTATE" [Field "Z"] (Val_Struct [("Z", Val_Symbolic 27%Z)]) Mk_annot;
    ReadReg "PSTATE" [Field "C"] (Val_Struct [("C", Val_Symbolic 5%Z)]) Mk_annot;
    ReadReg "PSTATE" [Field "V"] (Val_Struct [("V", Val_Symbolic 26%Z)]) Mk_annot;
    ReadReg "PSTATE" [Field "PAN"] (Val_Struct [("PAN", Val_Symbolic 18%Z)]) Mk_annot;
    ReadReg "PSTATE" [Field "SS"] (Val_Struct [("SS", Val_Symbolic 21%Z)]) Mk_annot;
    ReadReg "PSTATE" [Field "IL"] (Val_Struct [("IL", Val_Symbolic 13%Z)]) Mk_annot;
    Smt (Assert (Unop (Not) (Binop (Eq) (Val (Val_Symbolic 28%Z) Mk_annot) (Val (Val_Bits [BV{1%N} 0x1%Z]) Mk_annot) Mk_annot) Mk_annot)) Mk_annot;
    ReadReg "PSTATE" [Field "D"] (Val_Struct [("D", Val_Symbolic 6%Z)]) Mk_annot;
    ReadReg "PSTATE" [Field "A"] (Val_Struct [("A", Val_Symbolic 3%Z)]) Mk_annot;
    ReadReg "PSTATE" [Field "I"] (Val_Struct [("I", Val_Symbolic 12%Z)]) Mk_annot;
    ReadReg "PSTATE" [Field "F"] (Val_Struct [("F", Val_Symbolic 10%Z)]) Mk_annot;
    Smt (DefineConst 221%Z (Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Manyop (Bvmanyarith Bvor) [Val (Val_Bits [BV{32%N} 0x0%Z]) Mk_annot; Binop ((Bvarith Bvshl)) (Unop (ZeroExtend 28%N) (Manyop Concat [Val (Val_Symbolic 17%Z) Mk_annot; Manyop Concat [Val (Val_Symbolic 27%Z) Mk_annot; Manyop Concat [Val (Val_Symbolic 5%Z) Mk_annot; Val (Val_Symbolic 26%Z) Mk_annot] Mk_annot] Mk_annot] Mk_annot) Mk_annot) (Val (Val_Bits [BV{32%N} 0x1c%Z]) Mk_annot) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0xffbfffff%Z]) Mk_annot] Mk_annot; Binop ((Bvarith Bvshl)) (Unop (ZeroExtend 31%N) (Val (Val_Symbolic 18%Z) Mk_annot) Mk_annot) (Val (Val_Bits [BV{32%N} 0x16%Z]) Mk_annot) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0xffdfffff%Z]) Mk_annot] Mk_annot; Binop ((Bvarith Bvshl)) (Unop (ZeroExtend 31%N) (Val (Val_Symbolic 21%Z) Mk_annot) Mk_annot) (Val (Val_Bits [BV{32%N} 0x15%Z]) Mk_annot) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0xffefffff%Z]) Mk_annot] Mk_annot; Binop ((Bvarith Bvshl)) (Unop (ZeroExtend 31%N) (Val (Val_Symbolic 13%Z) Mk_annot) Mk_annot) (Val (Val_Bits [BV{32%N} 0x14%Z]) Mk_annot) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0xfffffc3f%Z]) Mk_annot] Mk_annot; Binop ((Bvarith Bvshl)) (Unop (ZeroExtend 28%N) (Manyop Concat [Val (Val_Symbolic 6%Z) Mk_annot; Manyop Concat [Val (Val_Symbolic 3%Z) Mk_annot; Manyop Concat [Val (Val_Symbolic 12%Z) Mk_annot; Val (Val_Symbolic 10%Z) Mk_annot] Mk_annot] Mk_annot] Mk_annot) Mk_annot) (Val (Val_Bits [BV{32%N} 0x6%Z]) Mk_annot) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0xffffffef%Z]) Mk_annot] Mk_annot; Binop ((Bvarith Bvshl)) (Unop (ZeroExtend 31%N) (Val (Val_Symbolic 28%Z) Mk_annot) Mk_annot) (Val (Val_Bits [BV{32%N} 0x4%Z]) Mk_annot) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0xfffffff3%Z]) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0x8%Z]) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0xfffffffe%Z]) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0x1%Z]) Mk_annot] Mk_annot)) Mk_annot;
    ReadReg "__currentInstrLength" [] (Val_I 4%Z 128%Z) Mk_annot;
    Smt (DefineConst 225%Z (Binop (Eq) (Val (Val_Symbolic 28%Z) Mk_annot) (Val (Val_Bits [BV{1%N} 0x1%Z]) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 225%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 225%Z) Mk_annot) Mk_annot)) Mk_annot;
    WriteReg "ESR_EL2" [] (Val_Bits [BV{32%N} 0x960000a1%Z]) Mk_annot;
    WriteReg "FAR_EL2" [] (Val_Symbolic 191%Z) Mk_annot;
    Smt (DeclareConst 230%Z (Ty_BitVec 40%N)) Mk_annot;
    Smt (DeclareConst 231%Z (Ty_BitVec 64%N)) Mk_annot;
    ReadReg "HPFAR_EL2" [] (Val_Symbolic 231%Z) Mk_annot;
    Smt (DefineConst 232%Z (Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Val (Val_Symbolic 231%Z) Mk_annot; Val (Val_Bits [BV{64%N} 0xfffff0000000000f%Z]) Mk_annot] Mk_annot; Binop ((Bvarith Bvshl)) (Unop (ZeroExtend 24%N) (Val (Val_Symbolic 230%Z) Mk_annot) Mk_annot) (Val (Val_Bits [BV{64%N} 0x4%Z]) Mk_annot) Mk_annot] Mk_annot)) Mk_annot;
    WriteReg "HPFAR_EL2" [] (Val_Symbolic 232%Z) Mk_annot;
    WriteReg "PSTATE" [Field "EL"] (Val_Struct [("EL", Val_Bits [BV{2%N} 0x2%Z])]) Mk_annot;
    WriteReg "PSTATE" [Field "nRW"] (Val_Struct [("nRW", Val_Bits [BV{1%N} 0x0%Z])]) Mk_annot;
    WriteReg "PSTATE" [Field "SP"] (Val_Struct [("SP", Val_Bits [BV{1%N} 0x1%Z])]) Mk_annot;
    ReadReg "PSTATE" [Field "nRW"] (Val_Struct [("nRW", Val_Bits [BV{1%N} 0x0%Z])]) Mk_annot;
    ReadReg "PSTATE" [Field "EL"] (Val_Struct [("EL", Val_Bits [BV{2%N} 0x2%Z])]) Mk_annot;
    WriteReg "SPSR_EL2" [] (Val_Symbolic 221%Z) Mk_annot;
    WriteReg "ELR_EL2" [] (Val_Symbolic 117%Z) Mk_annot;
    WriteReg "PSTATE" [Field "SS"] (Val_Struct [("SS", Val_Bits [BV{1%N} 0x0%Z])]) Mk_annot;
    WriteReg "PSTATE" [Field "D"] (Val_Struct [("D", Val_Bits [BV{1%N} 0x1%Z])]) Mk_annot;
    WriteReg "PSTATE" [Field "A"] (Val_Struct [("A", Val_Bits [BV{1%N} 0x1%Z])]) Mk_annot;
    WriteReg "PSTATE" [Field "I"] (Val_Struct [("I", Val_Bits [BV{1%N} 0x1%Z])]) Mk_annot;
    WriteReg "PSTATE" [Field "F"] (Val_Struct [("F", Val_Bits [BV{1%N} 0x1%Z])]) Mk_annot;
    WriteReg "PSTATE" [Field "IL"] (Val_Struct [("IL", Val_Bits [BV{1%N} 0x0%Z])]) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 204%Z) Mk_annot) Mk_annot)) Mk_annot;
    Barrier (Val_Enum ((Mk_enum_id 5%nat), Mk_enum_ctor 25%nat)) Mk_annot;
    ReadReg "VBAR_EL2" [] (Val_Bits [BV{64%N} 0x0%Z]) Mk_annot;
    BranchAddress (Val_Bits [BV{64%N} 0x200%Z]) Mk_annot;
    ReadReg "TCR_EL2" [] (Val_Bits [BV{64%N} 0x0%Z]) Mk_annot;
    WriteReg "_PC" [] (Val_Bits [BV{64%N} 0x200%Z]) Mk_annot;
    WriteReg "__PC_changed" [] (Val_Bool true) Mk_annot
  ];
  [
    Smt (DeclareConst 3%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 5%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 6%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 10%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 12%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 13%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 17%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 18%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 21%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 26%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 27%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 28%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (Assert (Binop (Eq) (Val (Val_Bits [BV{64%N} 0x0%Z]) Mk_annot) (Val (Val_Bits [BV{64%N} 0x0%Z]) Mk_annot) Mk_annot)) Mk_annot;
    Smt (DeclareConst 42%Z (Ty_BitVec 64%N)) Mk_annot;
    ReadReg "_PC" [] (Val_Symbolic 42%Z) Mk_annot;
    Smt (DefineConst 43%Z (Manyop (Bvmanyarith Bvadd) [Val (Val_Symbolic 42%Z) Mk_annot; Val (Val_Bits [BV{64%N} 0x3d4%Z]) Mk_annot] Mk_annot)) Mk_annot;
    ReadReg "PSTATE" [Field "EL"] (Val_Struct [("EL", Val_Bits [BV{2%N} 0x2%Z])]) Mk_annot;
    ReadReg "SCTLR_EL2" [] (Val_Bits [BV{64%N} 0x4000002%Z]) Mk_annot;
    Smt (DefineConst 74%Z (Unop (Not) (Binop (Eq) (Val (Val_Symbolic 43%Z) Mk_annot) (Manyop (Bvmanyarith Bvand) [Val (Val_Symbolic 43%Z) Mk_annot; Val (Val_Bits [BV{64%N} 0xfffffffffffffff8%Z]) Mk_annot] Mk_annot) Mk_annot) Mk_annot)) Mk_annot;
    Branch 0%Z "model/aarch64.sail 13242:4 - 13245:5" Mk_annot;
    Smt (Assert (Val (Val_Symbolic 74%Z) Mk_annot)) Mk_annot;
    Smt (DeclareConst 79%Z Ty_Bool) Mk_annot;
    ReadReg "CFG_ID_AA64PFR0_EL1_EL3" [] (Val_Bits [BV{4%N} 0x1%Z]) Mk_annot;
    ReadReg "SCR_EL3" [] (Val_Bits [BV{32%N} 0x0%Z]) Mk_annot;
    ReadReg "CFG_ID_AA64PFR0_EL1_EL2" [] (Val_Bits [BV{4%N} 0x1%Z]) Mk_annot;
    ReadReg "PSTATE" [Field "nRW"] (Val_Struct [("nRW", Val_Symbolic 28%Z)]) Mk_annot;
    Smt (DefineConst 111%Z (Binop (Eq) (Val (Val_Symbolic 28%Z) Mk_annot) (Val (Val_Bits [BV{1%N} 0x1%Z]) Mk_annot) Mk_annot)) Mk_annot;
    ReadReg "CFG_ID_AA64PFR0_EL1_EL0" [] (Val_Bits [BV{4%N} 0x1%Z]) Mk_annot;
    ReadReg "CFG_ID_AA64PFR0_EL1_EL1" [] (Val_Bits [BV{4%N} 0x1%Z]) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 111%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 111%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (DefineConst 114%Z (Binop (Eq) (Val (Val_Symbolic 28%Z) Mk_annot) (Val (Val_Bits [BV{1%N} 0x1%Z]) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 114%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 114%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (DefineConst 117%Z (Val (Val_Symbolic 42%Z) Mk_annot)) Mk_annot;
    Branch 1%Z "model/aarch_mem.sail 6794:41 - 6794:77" Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 79%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (DefineConst 191%Z (Val (Val_Symbolic 43%Z) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 79%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (DefineConst 204%Z (Binop (Eq) (Val (Val_Symbolic 28%Z) Mk_annot) (Val (Val_Bits [BV{1%N} 0x1%Z]) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 204%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 204%Z) Mk_annot) Mk_annot)) Mk_annot;
    ReadReg "PSTATE" [Field "SP"] (Val_Struct [("SP", Val_Bits [BV{1%N} 0x1%Z])]) Mk_annot;
    ReadReg "PSTATE" [Field "N"] (Val_Struct [("N", Val_Symbolic 17%Z)]) Mk_annot;
    ReadReg "PSTATE" [Field "Z"] (Val_Struct [("Z", Val_Symbolic 27%Z)]) Mk_annot;
    ReadReg "PSTATE" [Field "C"] (Val_Struct [("C", Val_Symbolic 5%Z)]) Mk_annot;
    ReadReg "PSTATE" [Field "V"] (Val_Struct [("V", Val_Symbolic 26%Z)]) Mk_annot;
    ReadReg "PSTATE" [Field "PAN"] (Val_Struct [("PAN", Val_Symbolic 18%Z)]) Mk_annot;
    ReadReg "PSTATE" [Field "SS"] (Val_Struct [("SS", Val_Symbolic 21%Z)]) Mk_annot;
    ReadReg "PSTATE" [Field "IL"] (Val_Struct [("IL", Val_Symbolic 13%Z)]) Mk_annot;
    Smt (Assert (Unop (Not) (Binop (Eq) (Val (Val_Symbolic 28%Z) Mk_annot) (Val (Val_Bits [BV{1%N} 0x1%Z]) Mk_annot) Mk_annot) Mk_annot)) Mk_annot;
    ReadReg "PSTATE" [Field "D"] (Val_Struct [("D", Val_Symbolic 6%Z)]) Mk_annot;
    ReadReg "PSTATE" [Field "A"] (Val_Struct [("A", Val_Symbolic 3%Z)]) Mk_annot;
    ReadReg "PSTATE" [Field "I"] (Val_Struct [("I", Val_Symbolic 12%Z)]) Mk_annot;
    ReadReg "PSTATE" [Field "F"] (Val_Struct [("F", Val_Symbolic 10%Z)]) Mk_annot;
    Smt (DefineConst 221%Z (Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Manyop (Bvmanyarith Bvor) [Val (Val_Bits [BV{32%N} 0x0%Z]) Mk_annot; Binop ((Bvarith Bvshl)) (Unop (ZeroExtend 28%N) (Manyop Concat [Val (Val_Symbolic 17%Z) Mk_annot; Manyop Concat [Val (Val_Symbolic 27%Z) Mk_annot; Manyop Concat [Val (Val_Symbolic 5%Z) Mk_annot; Val (Val_Symbolic 26%Z) Mk_annot] Mk_annot] Mk_annot] Mk_annot) Mk_annot) (Val (Val_Bits [BV{32%N} 0x1c%Z]) Mk_annot) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0xffbfffff%Z]) Mk_annot] Mk_annot; Binop ((Bvarith Bvshl)) (Unop (ZeroExtend 31%N) (Val (Val_Symbolic 18%Z) Mk_annot) Mk_annot) (Val (Val_Bits [BV{32%N} 0x16%Z]) Mk_annot) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0xffdfffff%Z]) Mk_annot] Mk_annot; Binop ((Bvarith Bvshl)) (Unop (ZeroExtend 31%N) (Val (Val_Symbolic 21%Z) Mk_annot) Mk_annot) (Val (Val_Bits [BV{32%N} 0x15%Z]) Mk_annot) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0xffefffff%Z]) Mk_annot] Mk_annot; Binop ((Bvarith Bvshl)) (Unop (ZeroExtend 31%N) (Val (Val_Symbolic 13%Z) Mk_annot) Mk_annot) (Val (Val_Bits [BV{32%N} 0x14%Z]) Mk_annot) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0xfffffc3f%Z]) Mk_annot] Mk_annot; Binop ((Bvarith Bvshl)) (Unop (ZeroExtend 28%N) (Manyop Concat [Val (Val_Symbolic 6%Z) Mk_annot; Manyop Concat [Val (Val_Symbolic 3%Z) Mk_annot; Manyop Concat [Val (Val_Symbolic 12%Z) Mk_annot; Val (Val_Symbolic 10%Z) Mk_annot] Mk_annot] Mk_annot] Mk_annot) Mk_annot) (Val (Val_Bits [BV{32%N} 0x6%Z]) Mk_annot) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0xffffffef%Z]) Mk_annot] Mk_annot; Binop ((Bvarith Bvshl)) (Unop (ZeroExtend 31%N) (Val (Val_Symbolic 28%Z) Mk_annot) Mk_annot) (Val (Val_Bits [BV{32%N} 0x4%Z]) Mk_annot) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0xfffffff3%Z]) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0x8%Z]) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0xfffffffe%Z]) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0x1%Z]) Mk_annot] Mk_annot)) Mk_annot;
    ReadReg "__currentInstrLength" [] (Val_I 4%Z 128%Z) Mk_annot;
    Smt (DefineConst 225%Z (Binop (Eq) (Val (Val_Symbolic 28%Z) Mk_annot) (Val (Val_Bits [BV{1%N} 0x1%Z]) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 225%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 225%Z) Mk_annot) Mk_annot)) Mk_annot;
    WriteReg "ESR_EL2" [] (Val_Bits [BV{32%N} 0x96000021%Z]) Mk_annot;
    WriteReg "FAR_EL2" [] (Val_Symbolic 191%Z) Mk_annot;
    Smt (DeclareConst 230%Z (Ty_BitVec 40%N)) Mk_annot;
    Smt (DeclareConst 231%Z (Ty_BitVec 64%N)) Mk_annot;
    ReadReg "HPFAR_EL2" [] (Val_Symbolic 231%Z) Mk_annot;
    Smt (DefineConst 232%Z (Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Val (Val_Symbolic 231%Z) Mk_annot; Val (Val_Bits [BV{64%N} 0xfffff0000000000f%Z]) Mk_annot] Mk_annot; Binop ((Bvarith Bvshl)) (Unop (ZeroExtend 24%N) (Val (Val_Symbolic 230%Z) Mk_annot) Mk_annot) (Val (Val_Bits [BV{64%N} 0x4%Z]) Mk_annot) Mk_annot] Mk_annot)) Mk_annot;
    WriteReg "HPFAR_EL2" [] (Val_Symbolic 232%Z) Mk_annot;
    WriteReg "PSTATE" [Field "EL"] (Val_Struct [("EL", Val_Bits [BV{2%N} 0x2%Z])]) Mk_annot;
    WriteReg "PSTATE" [Field "nRW"] (Val_Struct [("nRW", Val_Bits [BV{1%N} 0x0%Z])]) Mk_annot;
    WriteReg "PSTATE" [Field "SP"] (Val_Struct [("SP", Val_Bits [BV{1%N} 0x1%Z])]) Mk_annot;
    ReadReg "PSTATE" [Field "nRW"] (Val_Struct [("nRW", Val_Bits [BV{1%N} 0x0%Z])]) Mk_annot;
    ReadReg "PSTATE" [Field "EL"] (Val_Struct [("EL", Val_Bits [BV{2%N} 0x2%Z])]) Mk_annot;
    WriteReg "SPSR_EL2" [] (Val_Symbolic 221%Z) Mk_annot;
    WriteReg "ELR_EL2" [] (Val_Symbolic 117%Z) Mk_annot;
    WriteReg "PSTATE" [Field "SS"] (Val_Struct [("SS", Val_Bits [BV{1%N} 0x0%Z])]) Mk_annot;
    WriteReg "PSTATE" [Field "D"] (Val_Struct [("D", Val_Bits [BV{1%N} 0x1%Z])]) Mk_annot;
    WriteReg "PSTATE" [Field "A"] (Val_Struct [("A", Val_Bits [BV{1%N} 0x1%Z])]) Mk_annot;
    WriteReg "PSTATE" [Field "I"] (Val_Struct [("I", Val_Bits [BV{1%N} 0x1%Z])]) Mk_annot;
    WriteReg "PSTATE" [Field "F"] (Val_Struct [("F", Val_Bits [BV{1%N} 0x1%Z])]) Mk_annot;
    WriteReg "PSTATE" [Field "IL"] (Val_Struct [("IL", Val_Bits [BV{1%N} 0x0%Z])]) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 204%Z) Mk_annot) Mk_annot)) Mk_annot;
    Barrier (Val_Enum ((Mk_enum_id 5%nat), Mk_enum_ctor 25%nat)) Mk_annot;
    ReadReg "VBAR_EL2" [] (Val_Bits [BV{64%N} 0x0%Z]) Mk_annot;
    BranchAddress (Val_Bits [BV{64%N} 0x200%Z]) Mk_annot;
    ReadReg "TCR_EL2" [] (Val_Bits [BV{64%N} 0x0%Z]) Mk_annot;
    WriteReg "_PC" [] (Val_Bits [BV{64%N} 0x200%Z]) Mk_annot;
    WriteReg "__PC_changed" [] (Val_Bool true) Mk_annot
  ];
  [
    Smt (DeclareConst 3%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 5%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 6%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 10%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 12%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 13%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 17%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 18%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 21%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 26%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 27%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 28%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (Assert (Binop (Eq) (Val (Val_Bits [BV{64%N} 0x0%Z]) Mk_annot) (Val (Val_Bits [BV{64%N} 0x0%Z]) Mk_annot) Mk_annot)) Mk_annot;
    Smt (DeclareConst 42%Z (Ty_BitVec 64%N)) Mk_annot;
    ReadReg "_PC" [] (Val_Symbolic 42%Z) Mk_annot;
    Smt (DefineConst 43%Z (Manyop (Bvmanyarith Bvadd) [Val (Val_Symbolic 42%Z) Mk_annot; Val (Val_Bits [BV{64%N} 0x3d4%Z]) Mk_annot] Mk_annot)) Mk_annot;
    Smt (DefineConst 70%Z (Binop (Eq) (Val (Val_Symbolic 43%Z) Mk_annot) (Manyop (Bvmanyarith Bvand) [Val (Val_Symbolic 43%Z) Mk_annot; Val (Val_Bits [BV{64%N} 0xfffffffffffffff8%Z]) Mk_annot] Mk_annot) Mk_annot)) Mk_annot;
    ReadReg "PSTATE" [Field "EL"] (Val_Struct [("EL", Val_Bits [BV{2%N} 0x2%Z])]) Mk_annot;
    ReadReg "SCTLR_EL2" [] (Val_Bits [BV{64%N} 0x4000002%Z]) Mk_annot;
    Smt (DefineConst 74%Z (Unop (Not) (Val (Val_Symbolic 70%Z) Mk_annot) Mk_annot)) Mk_annot;
    Branch 0%Z "model/aarch64.sail 13242:4 - 13245:5" Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 74%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Unop (Not) (Val (Val_Symbolic 70%Z) Mk_annot) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Binop (Eq) (Val (Val_Symbolic 43%Z) Mk_annot) (Manyop (Bvmanyarith Bvand) [Val (Val_Symbolic 43%Z) Mk_annot; Val (Val_Bits [BV{64%N} 0xfffffffffffffff8%Z]) Mk_annot] Mk_annot) Mk_annot)) Mk_annot;
    ReadReg "CFG_ID_AA64PFR0_EL1_EL2" [] (Val_Bits [BV{4%N} 0x1%Z]) Mk_annot;
    ReadReg "CFG_ID_AA64PFR0_EL1_EL3" [] (Val_Bits [BV{4%N} 0x1%Z]) Mk_annot;
    ReadReg "PSTATE" [Field "nRW"] (Val_Struct [("nRW", Val_Symbolic 28%Z)]) Mk_annot;
    Smt (DefineConst 282%Z (Binop (Eq) (Val (Val_Symbolic 28%Z) Mk_annot) (Val (Val_Bits [BV{1%N} 0x1%Z]) Mk_annot) Mk_annot)) Mk_annot;
    ReadReg "CFG_ID_AA64PFR0_EL1_EL0" [] (Val_Bits [BV{4%N} 0x1%Z]) Mk_annot;
    ReadReg "CFG_ID_AA64PFR0_EL1_EL1" [] (Val_Bits [BV{4%N} 0x1%Z]) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 282%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 282%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (DefineConst 285%Z (Binop (Eq) (Val (Val_Symbolic 28%Z) Mk_annot) (Val (Val_Bits [BV{1%N} 0x1%Z]) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 285%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 285%Z) Mk_annot) Mk_annot)) Mk_annot;
    ReadReg "SCR_EL3" [] (Val_Bits [BV{32%N} 0x0%Z]) Mk_annot;
    ReadReg "TCR_EL2" [] (Val_Bits [BV{64%N} 0x0%Z]) Mk_annot;
    Smt (DefineConst 896%Z (Unop (Not) (Binop (Eq) (Unop (Extract 63%N 52%N) (Val (Val_Symbolic 43%Z) Mk_annot) Mk_annot) (Val (Val_Bits [BV{12%N} 0x0%Z]) Mk_annot) Mk_annot) Mk_annot)) Mk_annot;
    Branch 1%Z "model/aarch_mem.sail 6443:4 - 6452:5" Mk_annot;
    Smt (Assert (Val (Val_Symbolic 896%Z) Mk_annot)) Mk_annot;
    Smt (DefineConst 931%Z (Binop (Eq) (Val (Val_Symbolic 28%Z) Mk_annot) (Val (Val_Bits [BV{1%N} 0x1%Z]) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 931%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 931%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Unop (Not) (Val (Val_Symbolic 70%Z) Mk_annot) Mk_annot) Mk_annot)) Mk_annot;
    Smt (DefineConst 1140%Z (Binop (Eq) (Val (Val_Symbolic 28%Z) Mk_annot) (Val (Val_Bits [BV{1%N} 0x1%Z]) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 1140%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 1140%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (DefineConst 1143%Z (Binop (Eq) (Val (Val_Symbolic 28%Z) Mk_annot) (Val (Val_Bits [BV{1%N} 0x1%Z]) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 1143%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 1143%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (DefineConst 1146%Z (Val (Val_Symbolic 42%Z) Mk_annot)) Mk_annot;
    Smt (DefineConst 1220%Z (Val (Val_Symbolic 43%Z) Mk_annot)) Mk_annot;
    Smt (DefineConst 1233%Z (Binop (Eq) (Val (Val_Symbolic 28%Z) Mk_annot) (Val (Val_Bits [BV{1%N} 0x1%Z]) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 1233%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 1233%Z) Mk_annot) Mk_annot)) Mk_annot;
    ReadReg "PSTATE" [Field "SP"] (Val_Struct [("SP", Val_Bits [BV{1%N} 0x1%Z])]) Mk_annot;
    ReadReg "PSTATE" [Field "N"] (Val_Struct [("N", Val_Symbolic 17%Z)]) Mk_annot;
    ReadReg "PSTATE" [Field "Z"] (Val_Struct [("Z", Val_Symbolic 27%Z)]) Mk_annot;
    ReadReg "PSTATE" [Field "C"] (Val_Struct [("C", Val_Symbolic 5%Z)]) Mk_annot;
    ReadReg "PSTATE" [Field "V"] (Val_Struct [("V", Val_Symbolic 26%Z)]) Mk_annot;
    ReadReg "PSTATE" [Field "PAN"] (Val_Struct [("PAN", Val_Symbolic 18%Z)]) Mk_annot;
    ReadReg "PSTATE" [Field "SS"] (Val_Struct [("SS", Val_Symbolic 21%Z)]) Mk_annot;
    ReadReg "PSTATE" [Field "IL"] (Val_Struct [("IL", Val_Symbolic 13%Z)]) Mk_annot;
    Smt (Assert (Unop (Not) (Binop (Eq) (Val (Val_Symbolic 28%Z) Mk_annot) (Val (Val_Bits [BV{1%N} 0x1%Z]) Mk_annot) Mk_annot) Mk_annot)) Mk_annot;
    ReadReg "PSTATE" [Field "D"] (Val_Struct [("D", Val_Symbolic 6%Z)]) Mk_annot;
    ReadReg "PSTATE" [Field "A"] (Val_Struct [("A", Val_Symbolic 3%Z)]) Mk_annot;
    ReadReg "PSTATE" [Field "I"] (Val_Struct [("I", Val_Symbolic 12%Z)]) Mk_annot;
    ReadReg "PSTATE" [Field "F"] (Val_Struct [("F", Val_Symbolic 10%Z)]) Mk_annot;
    Smt (DefineConst 1250%Z (Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Manyop (Bvmanyarith Bvor) [Val (Val_Bits [BV{32%N} 0x0%Z]) Mk_annot; Binop ((Bvarith Bvshl)) (Unop (ZeroExtend 28%N) (Manyop Concat [Val (Val_Symbolic 17%Z) Mk_annot; Manyop Concat [Val (Val_Symbolic 27%Z) Mk_annot; Manyop Concat [Val (Val_Symbolic 5%Z) Mk_annot; Val (Val_Symbolic 26%Z) Mk_annot] Mk_annot] Mk_annot] Mk_annot) Mk_annot) (Val (Val_Bits [BV{32%N} 0x1c%Z]) Mk_annot) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0xffbfffff%Z]) Mk_annot] Mk_annot; Binop ((Bvarith Bvshl)) (Unop (ZeroExtend 31%N) (Val (Val_Symbolic 18%Z) Mk_annot) Mk_annot) (Val (Val_Bits [BV{32%N} 0x16%Z]) Mk_annot) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0xffdfffff%Z]) Mk_annot] Mk_annot; Binop ((Bvarith Bvshl)) (Unop (ZeroExtend 31%N) (Val (Val_Symbolic 21%Z) Mk_annot) Mk_annot) (Val (Val_Bits [BV{32%N} 0x15%Z]) Mk_annot) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0xffefffff%Z]) Mk_annot] Mk_annot; Binop ((Bvarith Bvshl)) (Unop (ZeroExtend 31%N) (Val (Val_Symbolic 13%Z) Mk_annot) Mk_annot) (Val (Val_Bits [BV{32%N} 0x14%Z]) Mk_annot) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0xfffffc3f%Z]) Mk_annot] Mk_annot; Binop ((Bvarith Bvshl)) (Unop (ZeroExtend 28%N) (Manyop Concat [Val (Val_Symbolic 6%Z) Mk_annot; Manyop Concat [Val (Val_Symbolic 3%Z) Mk_annot; Manyop Concat [Val (Val_Symbolic 12%Z) Mk_annot; Val (Val_Symbolic 10%Z) Mk_annot] Mk_annot] Mk_annot] Mk_annot) Mk_annot) (Val (Val_Bits [BV{32%N} 0x6%Z]) Mk_annot) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0xffffffef%Z]) Mk_annot] Mk_annot; Binop ((Bvarith Bvshl)) (Unop (ZeroExtend 31%N) (Val (Val_Symbolic 28%Z) Mk_annot) Mk_annot) (Val (Val_Bits [BV{32%N} 0x4%Z]) Mk_annot) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0xfffffff3%Z]) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0x8%Z]) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0xfffffffe%Z]) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0x1%Z]) Mk_annot] Mk_annot)) Mk_annot;
    ReadReg "__currentInstrLength" [] (Val_I 4%Z 128%Z) Mk_annot;
    Smt (DefineConst 1254%Z (Binop (Eq) (Val (Val_Symbolic 28%Z) Mk_annot) (Val (Val_Bits [BV{1%N} 0x1%Z]) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 1254%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 1254%Z) Mk_annot) Mk_annot)) Mk_annot;
    WriteReg "ESR_EL2" [] (Val_Bits [BV{32%N} 0x96000000%Z]) Mk_annot;
    WriteReg "FAR_EL2" [] (Val_Symbolic 1220%Z) Mk_annot;
    Smt (DeclareConst 1259%Z (Ty_BitVec 40%N)) Mk_annot;
    Smt (DeclareConst 1260%Z (Ty_BitVec 64%N)) Mk_annot;
    ReadReg "HPFAR_EL2" [] (Val_Symbolic 1260%Z) Mk_annot;
    Smt (DefineConst 1261%Z (Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Val (Val_Symbolic 1260%Z) Mk_annot; Val (Val_Bits [BV{64%N} 0xfffff0000000000f%Z]) Mk_annot] Mk_annot; Binop ((Bvarith Bvshl)) (Unop (ZeroExtend 24%N) (Val (Val_Symbolic 1259%Z) Mk_annot) Mk_annot) (Val (Val_Bits [BV{64%N} 0x4%Z]) Mk_annot) Mk_annot] Mk_annot)) Mk_annot;
    WriteReg "HPFAR_EL2" [] (Val_Symbolic 1261%Z) Mk_annot;
    WriteReg "PSTATE" [Field "EL"] (Val_Struct [("EL", Val_Bits [BV{2%N} 0x2%Z])]) Mk_annot;
    WriteReg "PSTATE" [Field "nRW"] (Val_Struct [("nRW", Val_Bits [BV{1%N} 0x0%Z])]) Mk_annot;
    WriteReg "PSTATE" [Field "SP"] (Val_Struct [("SP", Val_Bits [BV{1%N} 0x1%Z])]) Mk_annot;
    ReadReg "PSTATE" [Field "nRW"] (Val_Struct [("nRW", Val_Bits [BV{1%N} 0x0%Z])]) Mk_annot;
    ReadReg "PSTATE" [Field "EL"] (Val_Struct [("EL", Val_Bits [BV{2%N} 0x2%Z])]) Mk_annot;
    WriteReg "SPSR_EL2" [] (Val_Symbolic 1250%Z) Mk_annot;
    WriteReg "ELR_EL2" [] (Val_Symbolic 1146%Z) Mk_annot;
    WriteReg "PSTATE" [Field "SS"] (Val_Struct [("SS", Val_Bits [BV{1%N} 0x0%Z])]) Mk_annot;
    WriteReg "PSTATE" [Field "D"] (Val_Struct [("D", Val_Bits [BV{1%N} 0x1%Z])]) Mk_annot;
    WriteReg "PSTATE" [Field "A"] (Val_Struct [("A", Val_Bits [BV{1%N} 0x1%Z])]) Mk_annot;
    WriteReg "PSTATE" [Field "I"] (Val_Struct [("I", Val_Bits [BV{1%N} 0x1%Z])]) Mk_annot;
    WriteReg "PSTATE" [Field "F"] (Val_Struct [("F", Val_Bits [BV{1%N} 0x1%Z])]) Mk_annot;
    WriteReg "PSTATE" [Field "IL"] (Val_Struct [("IL", Val_Bits [BV{1%N} 0x0%Z])]) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 1233%Z) Mk_annot) Mk_annot)) Mk_annot;
    Barrier (Val_Enum ((Mk_enum_id 7%nat), Mk_enum_ctor 25%nat)) Mk_annot;
    ReadReg "VBAR_EL2" [] (Val_Bits [BV{64%N} 0x0%Z]) Mk_annot;
    BranchAddress (Val_Bits [BV{64%N} 0x200%Z]) Mk_annot;
    WriteReg "_PC" [] (Val_Bits [BV{64%N} 0x200%Z]) Mk_annot;
    WriteReg "__PC_changed" [] (Val_Bool true) Mk_annot
  ];
  [
    Smt (DeclareConst 6%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 28%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (Assert (Binop (Eq) (Val (Val_Bits [BV{64%N} 0x0%Z]) Mk_annot) (Val (Val_Bits [BV{64%N} 0x0%Z]) Mk_annot) Mk_annot)) Mk_annot;
    Smt (DeclareConst 42%Z (Ty_BitVec 64%N)) Mk_annot;
    ReadReg "_PC" [] (Val_Symbolic 42%Z) Mk_annot;
    Smt (DefineConst 43%Z (Manyop (Bvmanyarith Bvadd) [Val (Val_Symbolic 42%Z) Mk_annot; Val (Val_Bits [BV{64%N} 0x3d4%Z]) Mk_annot] Mk_annot)) Mk_annot;
    Smt (DefineConst 70%Z (Binop (Eq) (Val (Val_Symbolic 43%Z) Mk_annot) (Manyop (Bvmanyarith Bvand) [Val (Val_Symbolic 43%Z) Mk_annot; Val (Val_Bits [BV{64%N} 0xfffffffffffffff8%Z]) Mk_annot] Mk_annot) Mk_annot)) Mk_annot;
    ReadReg "PSTATE" [Field "EL"] (Val_Struct [("EL", Val_Bits [BV{2%N} 0x2%Z])]) Mk_annot;
    ReadReg "SCTLR_EL2" [] (Val_Bits [BV{64%N} 0x4000002%Z]) Mk_annot;
    Smt (DefineConst 74%Z (Unop (Not) (Val (Val_Symbolic 70%Z) Mk_annot) Mk_annot)) Mk_annot;
    Branch 0%Z "model/aarch64.sail 13242:4 - 13245:5" Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 74%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Unop (Not) (Val (Val_Symbolic 70%Z) Mk_annot) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Binop (Eq) (Val (Val_Symbolic 43%Z) Mk_annot) (Manyop (Bvmanyarith Bvand) [Val (Val_Symbolic 43%Z) Mk_annot; Val (Val_Bits [BV{64%N} 0xfffffffffffffff8%Z]) Mk_annot] Mk_annot) Mk_annot)) Mk_annot;
    ReadReg "CFG_ID_AA64PFR0_EL1_EL2" [] (Val_Bits [BV{4%N} 0x1%Z]) Mk_annot;
    ReadReg "CFG_ID_AA64PFR0_EL1_EL3" [] (Val_Bits [BV{4%N} 0x1%Z]) Mk_annot;
    ReadReg "PSTATE" [Field "nRW"] (Val_Struct [("nRW", Val_Symbolic 28%Z)]) Mk_annot;
    Smt (DefineConst 282%Z (Binop (Eq) (Val (Val_Symbolic 28%Z) Mk_annot) (Val (Val_Bits [BV{1%N} 0x1%Z]) Mk_annot) Mk_annot)) Mk_annot;
    ReadReg "CFG_ID_AA64PFR0_EL1_EL0" [] (Val_Bits [BV{4%N} 0x1%Z]) Mk_annot;
    ReadReg "CFG_ID_AA64PFR0_EL1_EL1" [] (Val_Bits [BV{4%N} 0x1%Z]) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 282%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 282%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (DefineConst 285%Z (Binop (Eq) (Val (Val_Symbolic 28%Z) Mk_annot) (Val (Val_Bits [BV{1%N} 0x1%Z]) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 285%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 285%Z) Mk_annot) Mk_annot)) Mk_annot;
    ReadReg "SCR_EL3" [] (Val_Bits [BV{32%N} 0x0%Z]) Mk_annot;
    ReadReg "TCR_EL2" [] (Val_Bits [BV{64%N} 0x0%Z]) Mk_annot;
    Smt (DefineConst 896%Z (Unop (Not) (Binop (Eq) (Unop (Extract 63%N 52%N) (Val (Val_Symbolic 43%Z) Mk_annot) Mk_annot) (Val (Val_Bits [BV{12%N} 0x0%Z]) Mk_annot) Mk_annot) Mk_annot)) Mk_annot;
    Branch 1%Z "model/aarch_mem.sail 6443:4 - 6452:5" Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 896%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (DefineConst 897%Z (Binop (Eq) (Val (Val_Symbolic 28%Z) Mk_annot) (Val (Val_Bits [BV{1%N} 0x1%Z]) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 897%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 897%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (DefineConst 900%Z (Binop (Eq) (Val (Val_Symbolic 28%Z) Mk_annot) (Val (Val_Bits [BV{1%N} 0x1%Z]) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 900%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 900%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (DefineConst 929%Z (Binop (Eq) (Val (Val_Symbolic 28%Z) Mk_annot) (Val (Val_Bits [BV{1%N} 0x1%Z]) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 929%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 929%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (DefineConst 932%Z (Binop (Eq) (Val (Val_Symbolic 28%Z) Mk_annot) (Val (Val_Bits [BV{1%N} 0x1%Z]) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 932%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 932%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (DefineConst 971%Z (Binop (Eq) (Val (Val_Symbolic 28%Z) Mk_annot) (Val (Val_Bits [BV{1%N} 0x1%Z]) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 971%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 971%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Unop (Not) (Val (Val_Symbolic 70%Z) Mk_annot) Mk_annot) Mk_annot)) Mk_annot;
    Smt (DefineConst 1179%Z (Binop (Eq) (Val (Val_Symbolic 28%Z) Mk_annot) (Val (Val_Bits [BV{1%N} 0x1%Z]) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 1179%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 1179%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (DefineConst 1182%Z (Binop (Eq) (Val (Val_Symbolic 28%Z) Mk_annot) (Val (Val_Bits [BV{1%N} 0x1%Z]) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 1182%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 1182%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (DefineConst 1221%Z (Binop (Eq) (Val (Val_Symbolic 28%Z) Mk_annot) (Val (Val_Bits [BV{1%N} 0x1%Z]) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 1221%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 1221%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (DefineConst 1224%Z (Binop (Eq) (Val (Val_Symbolic 28%Z) Mk_annot) (Val (Val_Bits [BV{1%N} 0x1%Z]) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 1224%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 1224%Z) Mk_annot) Mk_annot)) Mk_annot;
    ReadReg "PSTATE" [Field "D"] (Val_Struct [("D", Val_Symbolic 6%Z)]) Mk_annot;
    ReadReg "OSLSR_EL1" [] (Val_Bits [BV{32%N} 0x0%Z]) Mk_annot;
    ReadReg "OSDLR_EL1" [] (Val_Bits [BV{32%N} 0x0%Z]) Mk_annot;
    ReadReg "EDSCR" [] (Val_Bits [BV{32%N} 0x0%Z]) Mk_annot;
    Smt (DefineConst 1259%Z (Binop (Eq) (Val (Val_Symbolic 28%Z) Mk_annot) (Val (Val_Bits [BV{1%N} 0x1%Z]) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 1259%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 1259%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (DefineConst 1262%Z (Binop (Eq) (Val (Val_Symbolic 28%Z) Mk_annot) (Val (Val_Bits [BV{1%N} 0x1%Z]) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 1262%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 1262%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (DeclareConst 1304%Z (Ty_BitVec 56%N)) Mk_annot;
    Smt (DefineConst 1313%Z (Unop (ZeroExtend 8%N) (Manyop Concat [Val (Val_Bits [BV{4%N} 0x0%Z]) Mk_annot; Unop (Extract 51%N 0%N) (Val (Val_Symbolic 43%Z) Mk_annot) Mk_annot] Mk_annot) Mk_annot)) Mk_annot;
    Smt (DeclareConst 1314%Z (Ty_BitVec 64%N)) Mk_annot;
    ReadMem (Val_Symbolic 1314%Z) (Val_Enum ((Mk_enum_id 6%nat), Mk_enum_ctor 0%nat)) (Val_Symbolic 1313%Z) 8%N None Mk_annot;
    Smt (DefineConst 1316%Z (Binop (Eq) (Val (Val_Symbolic 28%Z) Mk_annot) (Val (Val_Bits [BV{1%N} 0x1%Z]) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 1316%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 1316%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (DefineConst 1319%Z (Val (Val_Symbolic 1314%Z) Mk_annot)) Mk_annot;
    WriteReg "R5" [] (Val_Symbolic 1319%Z) Mk_annot
  ]
].
