From isla Require Import isla_lang.

Definition a7424 : list trc := [
  [
    AssumeReg "HCR_EL2" [] (RegVal_Base (Val_Bits [BV{64%N} 0x0%Z])) Mk_annot;
    AssumeReg "CFG_ID_AA64PFR0_EL1_EL3" [] (RegVal_Base (Val_Bits [BV{4%N} 0x1%Z])) Mk_annot;
    AssumeReg "CFG_ID_AA64PFR0_EL1_EL2" [] (RegVal_Base (Val_Bits [BV{4%N} 0x1%Z])) Mk_annot;
    AssumeReg "CFG_ID_AA64PFR0_EL1_EL1" [] (RegVal_Base (Val_Bits [BV{4%N} 0x1%Z])) Mk_annot;
    AssumeReg "CFG_ID_AA64PFR0_EL1_EL0" [] (RegVal_Base (Val_Bits [BV{4%N} 0x1%Z])) Mk_annot;
    AssumeReg "TCR_EL2" [] (RegVal_Base (Val_Bits [BV{64%N} 0x0%Z])) Mk_annot;
    AssumeReg "EDSCR" [] (RegVal_Base (Val_Bits [BV{32%N} 0x0%Z])) Mk_annot;
    AssumeReg "OSDLR_EL1" [] (RegVal_Base (Val_Bits [BV{32%N} 0x0%Z])) Mk_annot;
    AssumeReg "OSLSR_EL1" [] (RegVal_Base (Val_Bits [BV{32%N} 0x0%Z])) Mk_annot;
    Smt (DeclareConst 6%Z (Ty_BitVec 1%N)) Mk_annot;
    AssumeReg "PSTATE" [Field "EL"] (RegVal_Base (Val_Bits [BV{2%N} 0x2%Z])) Mk_annot;
    AssumeReg "PSTATE" [Field "nRW"] (RegVal_Base (Val_Bits [BV{1%N} 0x0%Z])) Mk_annot;
    AssumeReg "SCR_EL3" [] (RegVal_Base (Val_Bits [BV{32%N} 0x401%Z])) Mk_annot;
    AssumeReg "SCTLR_EL2" [] (RegVal_Base (Val_Bits [BV{64%N} 0x4000002%Z])) Mk_annot;
    Assume (AExp_Binop (Eq) (AExp_Manyop (Bvmanyarith Bvand) [AExp_Val (AVal_Bits [BV{64%N} 0x77f8%Z]) Mk_annot; AExp_Val (AVal_Bits [BV{64%N} 0xfff0000000000007%Z]) Mk_annot] Mk_annot) (AExp_Val (AVal_Bits [BV{64%N} 0x0%Z]) Mk_annot) Mk_annot) Mk_annot;
    Smt (Assert (Binop (Eq) (Val (Val_Bits [BV{64%N} 0x0%Z]) Mk_annot) (Val (Val_Bits [BV{64%N} 0x0%Z]) Mk_annot) Mk_annot)) Mk_annot;
    Smt (DeclareConst 42%Z (Ty_BitVec 64%N)) Mk_annot;
    ReadReg "_PC" [] (RegVal_Base (Val_Symbolic 42%Z)) Mk_annot;
    Smt (DefineConst 43%Z (Manyop (Bvmanyarith Bvadd) [Val (Val_Symbolic 42%Z) Mk_annot; Val (Val_Bits [BV{64%N} 0x3d4%Z]) Mk_annot] Mk_annot)) Mk_annot;
    Smt (DefineConst 70%Z (Binop (Eq) (Val (Val_Symbolic 43%Z) Mk_annot) (Manyop (Bvmanyarith Bvand) [Val (Val_Symbolic 43%Z) Mk_annot; Val (Val_Bits [BV{64%N} 0xfffffffffffffff8%Z]) Mk_annot] Mk_annot) Mk_annot)) Mk_annot;
    ReadReg "PSTATE" [Field "EL"] (RegVal_Struct [("EL", RegVal_Base (Val_Bits [BV{2%N} 0x2%Z]))]) Mk_annot;
    ReadReg "SCTLR_EL2" [] (RegVal_Base (Val_Bits [BV{64%N} 0x4000002%Z])) Mk_annot;
    Smt (DefineConst 74%Z (Unop (Not) (Val (Val_Symbolic 70%Z) Mk_annot) Mk_annot)) Mk_annot;
    Branch 0%Z "model/aarch64.sail 13242:4 - 13245:5" Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 74%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Unop (Not) (Val (Val_Symbolic 70%Z) Mk_annot) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Binop (Eq) (Val (Val_Symbolic 43%Z) Mk_annot) (Manyop (Bvmanyarith Bvand) [Val (Val_Symbolic 43%Z) Mk_annot; Val (Val_Bits [BV{64%N} 0xfffffffffffffff8%Z]) Mk_annot] Mk_annot) Mk_annot)) Mk_annot;
    ReadReg "CFG_ID_AA64PFR0_EL1_EL2" [] (RegVal_Base (Val_Bits [BV{4%N} 0x1%Z])) Mk_annot;
    ReadReg "CFG_ID_AA64PFR0_EL1_EL3" [] (RegVal_Base (Val_Bits [BV{4%N} 0x1%Z])) Mk_annot;
    ReadReg "PSTATE" [Field "nRW"] (RegVal_Struct [("nRW", RegVal_Base (Val_Bits [BV{1%N} 0x0%Z]))]) Mk_annot;
    ReadReg "CFG_ID_AA64PFR0_EL1_EL0" [] (RegVal_Base (Val_Bits [BV{4%N} 0x1%Z])) Mk_annot;
    ReadReg "CFG_ID_AA64PFR0_EL1_EL1" [] (RegVal_Base (Val_Bits [BV{4%N} 0x1%Z])) Mk_annot;
    ReadReg "SCR_EL3" [] (RegVal_Base (Val_Bits [BV{32%N} 0x401%Z])) Mk_annot;
    ReadReg "HCR_EL2" [] (RegVal_Base (Val_Bits [BV{64%N} 0x0%Z])) Mk_annot;
    ReadReg "TCR_EL2" [] (RegVal_Base (Val_Bits [BV{64%N} 0x0%Z])) Mk_annot;
    Smt (DefineConst 910%Z (Unop (Not) (Binop (Eq) (Unop (Extract 63%N 52%N) (Val (Val_Symbolic 43%Z) Mk_annot) Mk_annot) (Val (Val_Bits [BV{12%N} 0x0%Z]) Mk_annot) Mk_annot) Mk_annot)) Mk_annot;
    Branch 1%Z "model/aarch_mem.sail 6443:4 - 6452:5" Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 910%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Unop (Not) (Val (Val_Symbolic 70%Z) Mk_annot) Mk_annot) Mk_annot)) Mk_annot;
    ReadReg "PSTATE" [Field "D"] (RegVal_Struct [("D", RegVal_Base (Val_Symbolic 6%Z))]) Mk_annot;
    ReadReg "OSLSR_EL1" [] (RegVal_Base (Val_Bits [BV{32%N} 0x0%Z])) Mk_annot;
    ReadReg "OSDLR_EL1" [] (RegVal_Base (Val_Bits [BV{32%N} 0x0%Z])) Mk_annot;
    ReadReg "EDSCR" [] (RegVal_Base (Val_Bits [BV{32%N} 0x0%Z])) Mk_annot;
    Smt (DeclareConst 1311%Z (Ty_BitVec 56%N)) Mk_annot;
    Smt (DefineConst 1320%Z (Unop (ZeroExtend 8%N) (Manyop Concat [Val (Val_Bits [BV{4%N} 0x0%Z]) Mk_annot; Unop (Extract 51%N 0%N) (Val (Val_Symbolic 43%Z) Mk_annot) Mk_annot] Mk_annot) Mk_annot)) Mk_annot;
    Smt (DeclareConst 1321%Z (Ty_BitVec 64%N)) Mk_annot;
    ReadMem (RegVal_Base (Val_Symbolic 1321%Z)) (RegVal_Base (Val_Enum ((Mk_enum_id 6%nat), Mk_enum_ctor 0%nat))) (RegVal_Base (Val_Symbolic 1320%Z)) 8%N None Mk_annot;
    Smt (DefineConst 1324%Z (Val (Val_Symbolic 1321%Z) Mk_annot)) Mk_annot;
    WriteReg "R5" [] (RegVal_Base (Val_Symbolic 1324%Z)) Mk_annot;
    Smt (DefineConst 1325%Z (Manyop (Bvmanyarith Bvadd) [Val (Val_Symbolic 42%Z) Mk_annot; Val (Val_Bits [BV{64%N} 0x4%Z]) Mk_annot] Mk_annot)) Mk_annot;
    WriteReg "_PC" [] (RegVal_Base (Val_Symbolic 1325%Z)) Mk_annot
  ];
  [
    AssumeReg "VBAR_EL2" [] (RegVal_Base (Val_Bits [BV{64%N} 0x0%Z])) Mk_annot;
    AssumeReg "HCR_EL2" [] (RegVal_Base (Val_Bits [BV{64%N} 0x0%Z])) Mk_annot;
    AssumeReg "CFG_ID_AA64PFR0_EL1_EL3" [] (RegVal_Base (Val_Bits [BV{4%N} 0x1%Z])) Mk_annot;
    AssumeReg "CFG_ID_AA64PFR0_EL1_EL2" [] (RegVal_Base (Val_Bits [BV{4%N} 0x1%Z])) Mk_annot;
    AssumeReg "CFG_ID_AA64PFR0_EL1_EL1" [] (RegVal_Base (Val_Bits [BV{4%N} 0x1%Z])) Mk_annot;
    AssumeReg "CFG_ID_AA64PFR0_EL1_EL0" [] (RegVal_Base (Val_Bits [BV{4%N} 0x1%Z])) Mk_annot;
    AssumeReg "TCR_EL2" [] (RegVal_Base (Val_Bits [BV{64%N} 0x0%Z])) Mk_annot;
    Smt (DeclareConst 3%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 5%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 6%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 10%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 12%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 13%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 17%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 18%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 21%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 26%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 27%Z (Ty_BitVec 1%N)) Mk_annot;
    AssumeReg "PSTATE" [Field "EL"] (RegVal_Base (Val_Bits [BV{2%N} 0x2%Z])) Mk_annot;
    AssumeReg "PSTATE" [Field "SP"] (RegVal_Base (Val_Bits [BV{1%N} 0x1%Z])) Mk_annot;
    AssumeReg "PSTATE" [Field "nRW"] (RegVal_Base (Val_Bits [BV{1%N} 0x0%Z])) Mk_annot;
    AssumeReg "SCR_EL3" [] (RegVal_Base (Val_Bits [BV{32%N} 0x401%Z])) Mk_annot;
    AssumeReg "SCTLR_EL2" [] (RegVal_Base (Val_Bits [BV{64%N} 0x4000002%Z])) Mk_annot;
    Assume (AExp_Binop (Eq) (AExp_Manyop (Bvmanyarith Bvand) [AExp_Val (AVal_Bits [BV{64%N} 0x77f8%Z]) Mk_annot; AExp_Val (AVal_Bits [BV{64%N} 0xfff0000000000007%Z]) Mk_annot] Mk_annot) (AExp_Val (AVal_Bits [BV{64%N} 0x0%Z]) Mk_annot) Mk_annot) Mk_annot;
    Smt (Assert (Binop (Eq) (Val (Val_Bits [BV{64%N} 0x0%Z]) Mk_annot) (Val (Val_Bits [BV{64%N} 0x0%Z]) Mk_annot) Mk_annot)) Mk_annot;
    Smt (DeclareConst 42%Z (Ty_BitVec 64%N)) Mk_annot;
    ReadReg "_PC" [] (RegVal_Base (Val_Symbolic 42%Z)) Mk_annot;
    Smt (DefineConst 43%Z (Manyop (Bvmanyarith Bvadd) [Val (Val_Symbolic 42%Z) Mk_annot; Val (Val_Bits [BV{64%N} 0x3d4%Z]) Mk_annot] Mk_annot)) Mk_annot;
    ReadReg "PSTATE" [Field "EL"] (RegVal_Struct [("EL", RegVal_Base (Val_Bits [BV{2%N} 0x2%Z]))]) Mk_annot;
    ReadReg "SCTLR_EL2" [] (RegVal_Base (Val_Bits [BV{64%N} 0x4000002%Z])) Mk_annot;
    Smt (DefineConst 74%Z (Unop (Not) (Binop (Eq) (Val (Val_Symbolic 43%Z) Mk_annot) (Manyop (Bvmanyarith Bvand) [Val (Val_Symbolic 43%Z) Mk_annot; Val (Val_Bits [BV{64%N} 0xfffffffffffffff8%Z]) Mk_annot] Mk_annot) Mk_annot) Mk_annot)) Mk_annot;
    Branch 0%Z "model/aarch64.sail 13242:4 - 13245:5" Mk_annot;
    Smt (Assert (Val (Val_Symbolic 74%Z) Mk_annot)) Mk_annot;
    Smt (DeclareConst 79%Z Ty_Bool) Mk_annot;
    ReadReg "CFG_ID_AA64PFR0_EL1_EL3" [] (RegVal_Base (Val_Bits [BV{4%N} 0x1%Z])) Mk_annot;
    ReadReg "SCR_EL3" [] (RegVal_Base (Val_Bits [BV{32%N} 0x401%Z])) Mk_annot;
    ReadReg "CFG_ID_AA64PFR0_EL1_EL2" [] (RegVal_Base (Val_Bits [BV{4%N} 0x1%Z])) Mk_annot;
    ReadReg "PSTATE" [Field "nRW"] (RegVal_Struct [("nRW", RegVal_Base (Val_Bits [BV{1%N} 0x0%Z]))]) Mk_annot;
    ReadReg "CFG_ID_AA64PFR0_EL1_EL0" [] (RegVal_Base (Val_Bits [BV{4%N} 0x1%Z])) Mk_annot;
    ReadReg "CFG_ID_AA64PFR0_EL1_EL1" [] (RegVal_Base (Val_Bits [BV{4%N} 0x1%Z])) Mk_annot;
    Smt (DefineConst 112%Z (Val (Val_Symbolic 42%Z) Mk_annot)) Mk_annot;
    Branch 1%Z "model/aarch_mem.sail 6794:41 - 6794:77" Mk_annot;
    Smt (Assert (Val (Val_Symbolic 79%Z) Mk_annot)) Mk_annot;
    Smt (DefineConst 186%Z (Val (Val_Symbolic 43%Z) Mk_annot)) Mk_annot;
    Smt (Assert (Val (Val_Symbolic 79%Z) Mk_annot)) Mk_annot;
    ReadReg "PSTATE" [Field "SP"] (RegVal_Struct [("SP", RegVal_Base (Val_Bits [BV{1%N} 0x1%Z]))]) Mk_annot;
    ReadReg "PSTATE" [Field "N"] (RegVal_Struct [("N", RegVal_Base (Val_Symbolic 17%Z))]) Mk_annot;
    ReadReg "PSTATE" [Field "Z"] (RegVal_Struct [("Z", RegVal_Base (Val_Symbolic 27%Z))]) Mk_annot;
    ReadReg "PSTATE" [Field "C"] (RegVal_Struct [("C", RegVal_Base (Val_Symbolic 5%Z))]) Mk_annot;
    ReadReg "PSTATE" [Field "V"] (RegVal_Struct [("V", RegVal_Base (Val_Symbolic 26%Z))]) Mk_annot;
    ReadReg "PSTATE" [Field "PAN"] (RegVal_Struct [("PAN", RegVal_Base (Val_Symbolic 18%Z))]) Mk_annot;
    ReadReg "PSTATE" [Field "SS"] (RegVal_Struct [("SS", RegVal_Base (Val_Symbolic 21%Z))]) Mk_annot;
    ReadReg "PSTATE" [Field "IL"] (RegVal_Struct [("IL", RegVal_Base (Val_Symbolic 13%Z))]) Mk_annot;
    ReadReg "PSTATE" [Field "D"] (RegVal_Struct [("D", RegVal_Base (Val_Symbolic 6%Z))]) Mk_annot;
    ReadReg "PSTATE" [Field "A"] (RegVal_Struct [("A", RegVal_Base (Val_Symbolic 3%Z))]) Mk_annot;
    ReadReg "PSTATE" [Field "I"] (RegVal_Struct [("I", RegVal_Base (Val_Symbolic 12%Z))]) Mk_annot;
    ReadReg "PSTATE" [Field "F"] (RegVal_Struct [("F", RegVal_Base (Val_Symbolic 10%Z))]) Mk_annot;
    Smt (DefineConst 213%Z (Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Manyop (Bvmanyarith Bvor) [Val (Val_Bits [BV{32%N} 0x0%Z]) Mk_annot; Binop ((Bvarith Bvshl)) (Unop (ZeroExtend 28%N) (Manyop Concat [Val (Val_Symbolic 17%Z) Mk_annot; Manyop Concat [Val (Val_Symbolic 27%Z) Mk_annot; Manyop Concat [Val (Val_Symbolic 5%Z) Mk_annot; Val (Val_Symbolic 26%Z) Mk_annot] Mk_annot] Mk_annot] Mk_annot) Mk_annot) (Val (Val_Bits [BV{32%N} 0x1c%Z]) Mk_annot) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0xffbfffff%Z]) Mk_annot] Mk_annot; Binop ((Bvarith Bvshl)) (Unop (ZeroExtend 31%N) (Val (Val_Symbolic 18%Z) Mk_annot) Mk_annot) (Val (Val_Bits [BV{32%N} 0x16%Z]) Mk_annot) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0xffdfffff%Z]) Mk_annot] Mk_annot; Binop ((Bvarith Bvshl)) (Unop (ZeroExtend 31%N) (Val (Val_Symbolic 21%Z) Mk_annot) Mk_annot) (Val (Val_Bits [BV{32%N} 0x15%Z]) Mk_annot) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0xffefffff%Z]) Mk_annot] Mk_annot; Binop ((Bvarith Bvshl)) (Unop (ZeroExtend 31%N) (Val (Val_Symbolic 13%Z) Mk_annot) Mk_annot) (Val (Val_Bits [BV{32%N} 0x14%Z]) Mk_annot) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0xfffffc3f%Z]) Mk_annot] Mk_annot; Binop ((Bvarith Bvshl)) (Unop (ZeroExtend 28%N) (Manyop Concat [Val (Val_Symbolic 6%Z) Mk_annot; Manyop Concat [Val (Val_Symbolic 3%Z) Mk_annot; Manyop Concat [Val (Val_Symbolic 12%Z) Mk_annot; Val (Val_Symbolic 10%Z) Mk_annot] Mk_annot] Mk_annot] Mk_annot) Mk_annot) (Val (Val_Bits [BV{32%N} 0x6%Z]) Mk_annot) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0xffffffef%Z]) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0x0%Z]) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0xfffffff3%Z]) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0x8%Z]) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0xfffffffe%Z]) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0x1%Z]) Mk_annot] Mk_annot)) Mk_annot;
    WriteReg "ESR_EL2" [] (RegVal_Base (Val_Bits [BV{32%N} 0x960000a1%Z])) Mk_annot;
    WriteReg "FAR_EL2" [] (RegVal_Base (Val_Symbolic 186%Z)) Mk_annot;
    Smt (DeclareConst 220%Z (Ty_BitVec 40%N)) Mk_annot;
    Smt (DeclareConst 221%Z (Ty_BitVec 64%N)) Mk_annot;
    ReadReg "HPFAR_EL2" [] (RegVal_Base (Val_Symbolic 221%Z)) Mk_annot;
    Smt (DefineConst 222%Z (Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Val (Val_Symbolic 221%Z) Mk_annot; Val (Val_Bits [BV{64%N} 0xfffff0000000000f%Z]) Mk_annot] Mk_annot; Binop ((Bvarith Bvshl)) (Unop (ZeroExtend 24%N) (Val (Val_Symbolic 220%Z) Mk_annot) Mk_annot) (Val (Val_Bits [BV{64%N} 0x4%Z]) Mk_annot) Mk_annot] Mk_annot)) Mk_annot;
    WriteReg "HPFAR_EL2" [] (RegVal_Base (Val_Symbolic 222%Z)) Mk_annot;
    WriteReg "PSTATE" [Field "EL"] (RegVal_Struct [("EL", RegVal_Base (Val_Bits [BV{2%N} 0x2%Z]))]) Mk_annot;
    WriteReg "PSTATE" [Field "nRW"] (RegVal_Struct [("nRW", RegVal_Base (Val_Bits [BV{1%N} 0x0%Z]))]) Mk_annot;
    WriteReg "PSTATE" [Field "SP"] (RegVal_Struct [("SP", RegVal_Base (Val_Bits [BV{1%N} 0x1%Z]))]) Mk_annot;
    ReadReg "PSTATE" [Field "nRW"] (RegVal_Struct [("nRW", RegVal_Base (Val_Bits [BV{1%N} 0x0%Z]))]) Mk_annot;
    ReadReg "PSTATE" [Field "EL"] (RegVal_Struct [("EL", RegVal_Base (Val_Bits [BV{2%N} 0x2%Z]))]) Mk_annot;
    WriteReg "SPSR_EL2" [] (RegVal_Base (Val_Symbolic 213%Z)) Mk_annot;
    WriteReg "ELR_EL2" [] (RegVal_Base (Val_Symbolic 112%Z)) Mk_annot;
    WriteReg "PSTATE" [Field "SS"] (RegVal_Struct [("SS", RegVal_Base (Val_Bits [BV{1%N} 0x0%Z]))]) Mk_annot;
    WriteReg "PSTATE" [Field "D"] (RegVal_Struct [("D", RegVal_Base (Val_Bits [BV{1%N} 0x1%Z]))]) Mk_annot;
    WriteReg "PSTATE" [Field "A"] (RegVal_Struct [("A", RegVal_Base (Val_Bits [BV{1%N} 0x1%Z]))]) Mk_annot;
    WriteReg "PSTATE" [Field "I"] (RegVal_Struct [("I", RegVal_Base (Val_Bits [BV{1%N} 0x1%Z]))]) Mk_annot;
    WriteReg "PSTATE" [Field "F"] (RegVal_Struct [("F", RegVal_Base (Val_Bits [BV{1%N} 0x1%Z]))]) Mk_annot;
    WriteReg "PSTATE" [Field "IL"] (RegVal_Struct [("IL", RegVal_Base (Val_Bits [BV{1%N} 0x0%Z]))]) Mk_annot;
    ReadReg "HCR_EL2" [] (RegVal_Base (Val_Bits [BV{64%N} 0x0%Z])) Mk_annot;
    Barrier (RegVal_Base (Val_Enum ((Mk_enum_id 5%nat), Mk_enum_ctor 25%nat))) Mk_annot;
    ReadReg "VBAR_EL2" [] (RegVal_Base (Val_Bits [BV{64%N} 0x0%Z])) Mk_annot;
    BranchAddress (RegVal_Base (Val_Bits [BV{64%N} 0x200%Z])) Mk_annot;
    ReadReg "TCR_EL2" [] (RegVal_Base (Val_Bits [BV{64%N} 0x0%Z])) Mk_annot;
    WriteReg "_PC" [] (RegVal_Base (Val_Bits [BV{64%N} 0x200%Z])) Mk_annot
  ];
  [
    AssumeReg "VBAR_EL2" [] (RegVal_Base (Val_Bits [BV{64%N} 0x0%Z])) Mk_annot;
    AssumeReg "HCR_EL2" [] (RegVal_Base (Val_Bits [BV{64%N} 0x0%Z])) Mk_annot;
    AssumeReg "CFG_ID_AA64PFR0_EL1_EL3" [] (RegVal_Base (Val_Bits [BV{4%N} 0x1%Z])) Mk_annot;
    AssumeReg "CFG_ID_AA64PFR0_EL1_EL2" [] (RegVal_Base (Val_Bits [BV{4%N} 0x1%Z])) Mk_annot;
    AssumeReg "CFG_ID_AA64PFR0_EL1_EL1" [] (RegVal_Base (Val_Bits [BV{4%N} 0x1%Z])) Mk_annot;
    AssumeReg "CFG_ID_AA64PFR0_EL1_EL0" [] (RegVal_Base (Val_Bits [BV{4%N} 0x1%Z])) Mk_annot;
    AssumeReg "TCR_EL2" [] (RegVal_Base (Val_Bits [BV{64%N} 0x0%Z])) Mk_annot;
    Smt (DeclareConst 3%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 5%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 6%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 10%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 12%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 13%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 17%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 18%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 21%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 26%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 27%Z (Ty_BitVec 1%N)) Mk_annot;
    AssumeReg "PSTATE" [Field "EL"] (RegVal_Base (Val_Bits [BV{2%N} 0x2%Z])) Mk_annot;
    AssumeReg "PSTATE" [Field "SP"] (RegVal_Base (Val_Bits [BV{1%N} 0x1%Z])) Mk_annot;
    AssumeReg "PSTATE" [Field "nRW"] (RegVal_Base (Val_Bits [BV{1%N} 0x0%Z])) Mk_annot;
    AssumeReg "SCR_EL3" [] (RegVal_Base (Val_Bits [BV{32%N} 0x401%Z])) Mk_annot;
    AssumeReg "SCTLR_EL2" [] (RegVal_Base (Val_Bits [BV{64%N} 0x4000002%Z])) Mk_annot;
    Assume (AExp_Binop (Eq) (AExp_Manyop (Bvmanyarith Bvand) [AExp_Val (AVal_Bits [BV{64%N} 0x77f8%Z]) Mk_annot; AExp_Val (AVal_Bits [BV{64%N} 0xfff0000000000007%Z]) Mk_annot] Mk_annot) (AExp_Val (AVal_Bits [BV{64%N} 0x0%Z]) Mk_annot) Mk_annot) Mk_annot;
    Smt (Assert (Binop (Eq) (Val (Val_Bits [BV{64%N} 0x0%Z]) Mk_annot) (Val (Val_Bits [BV{64%N} 0x0%Z]) Mk_annot) Mk_annot)) Mk_annot;
    Smt (DeclareConst 42%Z (Ty_BitVec 64%N)) Mk_annot;
    ReadReg "_PC" [] (RegVal_Base (Val_Symbolic 42%Z)) Mk_annot;
    Smt (DefineConst 43%Z (Manyop (Bvmanyarith Bvadd) [Val (Val_Symbolic 42%Z) Mk_annot; Val (Val_Bits [BV{64%N} 0x3d4%Z]) Mk_annot] Mk_annot)) Mk_annot;
    ReadReg "PSTATE" [Field "EL"] (RegVal_Struct [("EL", RegVal_Base (Val_Bits [BV{2%N} 0x2%Z]))]) Mk_annot;
    ReadReg "SCTLR_EL2" [] (RegVal_Base (Val_Bits [BV{64%N} 0x4000002%Z])) Mk_annot;
    Smt (DefineConst 74%Z (Unop (Not) (Binop (Eq) (Val (Val_Symbolic 43%Z) Mk_annot) (Manyop (Bvmanyarith Bvand) [Val (Val_Symbolic 43%Z) Mk_annot; Val (Val_Bits [BV{64%N} 0xfffffffffffffff8%Z]) Mk_annot] Mk_annot) Mk_annot) Mk_annot)) Mk_annot;
    Branch 0%Z "model/aarch64.sail 13242:4 - 13245:5" Mk_annot;
    Smt (Assert (Val (Val_Symbolic 74%Z) Mk_annot)) Mk_annot;
    Smt (DeclareConst 79%Z Ty_Bool) Mk_annot;
    ReadReg "CFG_ID_AA64PFR0_EL1_EL3" [] (RegVal_Base (Val_Bits [BV{4%N} 0x1%Z])) Mk_annot;
    ReadReg "SCR_EL3" [] (RegVal_Base (Val_Bits [BV{32%N} 0x401%Z])) Mk_annot;
    ReadReg "CFG_ID_AA64PFR0_EL1_EL2" [] (RegVal_Base (Val_Bits [BV{4%N} 0x1%Z])) Mk_annot;
    ReadReg "PSTATE" [Field "nRW"] (RegVal_Struct [("nRW", RegVal_Base (Val_Bits [BV{1%N} 0x0%Z]))]) Mk_annot;
    ReadReg "CFG_ID_AA64PFR0_EL1_EL0" [] (RegVal_Base (Val_Bits [BV{4%N} 0x1%Z])) Mk_annot;
    ReadReg "CFG_ID_AA64PFR0_EL1_EL1" [] (RegVal_Base (Val_Bits [BV{4%N} 0x1%Z])) Mk_annot;
    Smt (DefineConst 112%Z (Val (Val_Symbolic 42%Z) Mk_annot)) Mk_annot;
    Branch 1%Z "model/aarch_mem.sail 6794:41 - 6794:77" Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 79%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (DefineConst 186%Z (Val (Val_Symbolic 43%Z) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 79%Z) Mk_annot) Mk_annot)) Mk_annot;
    ReadReg "PSTATE" [Field "SP"] (RegVal_Struct [("SP", RegVal_Base (Val_Bits [BV{1%N} 0x1%Z]))]) Mk_annot;
    ReadReg "PSTATE" [Field "N"] (RegVal_Struct [("N", RegVal_Base (Val_Symbolic 17%Z))]) Mk_annot;
    ReadReg "PSTATE" [Field "Z"] (RegVal_Struct [("Z", RegVal_Base (Val_Symbolic 27%Z))]) Mk_annot;
    ReadReg "PSTATE" [Field "C"] (RegVal_Struct [("C", RegVal_Base (Val_Symbolic 5%Z))]) Mk_annot;
    ReadReg "PSTATE" [Field "V"] (RegVal_Struct [("V", RegVal_Base (Val_Symbolic 26%Z))]) Mk_annot;
    ReadReg "PSTATE" [Field "PAN"] (RegVal_Struct [("PAN", RegVal_Base (Val_Symbolic 18%Z))]) Mk_annot;
    ReadReg "PSTATE" [Field "SS"] (RegVal_Struct [("SS", RegVal_Base (Val_Symbolic 21%Z))]) Mk_annot;
    ReadReg "PSTATE" [Field "IL"] (RegVal_Struct [("IL", RegVal_Base (Val_Symbolic 13%Z))]) Mk_annot;
    ReadReg "PSTATE" [Field "D"] (RegVal_Struct [("D", RegVal_Base (Val_Symbolic 6%Z))]) Mk_annot;
    ReadReg "PSTATE" [Field "A"] (RegVal_Struct [("A", RegVal_Base (Val_Symbolic 3%Z))]) Mk_annot;
    ReadReg "PSTATE" [Field "I"] (RegVal_Struct [("I", RegVal_Base (Val_Symbolic 12%Z))]) Mk_annot;
    ReadReg "PSTATE" [Field "F"] (RegVal_Struct [("F", RegVal_Base (Val_Symbolic 10%Z))]) Mk_annot;
    Smt (DefineConst 213%Z (Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Manyop (Bvmanyarith Bvor) [Val (Val_Bits [BV{32%N} 0x0%Z]) Mk_annot; Binop ((Bvarith Bvshl)) (Unop (ZeroExtend 28%N) (Manyop Concat [Val (Val_Symbolic 17%Z) Mk_annot; Manyop Concat [Val (Val_Symbolic 27%Z) Mk_annot; Manyop Concat [Val (Val_Symbolic 5%Z) Mk_annot; Val (Val_Symbolic 26%Z) Mk_annot] Mk_annot] Mk_annot] Mk_annot) Mk_annot) (Val (Val_Bits [BV{32%N} 0x1c%Z]) Mk_annot) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0xffbfffff%Z]) Mk_annot] Mk_annot; Binop ((Bvarith Bvshl)) (Unop (ZeroExtend 31%N) (Val (Val_Symbolic 18%Z) Mk_annot) Mk_annot) (Val (Val_Bits [BV{32%N} 0x16%Z]) Mk_annot) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0xffdfffff%Z]) Mk_annot] Mk_annot; Binop ((Bvarith Bvshl)) (Unop (ZeroExtend 31%N) (Val (Val_Symbolic 21%Z) Mk_annot) Mk_annot) (Val (Val_Bits [BV{32%N} 0x15%Z]) Mk_annot) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0xffefffff%Z]) Mk_annot] Mk_annot; Binop ((Bvarith Bvshl)) (Unop (ZeroExtend 31%N) (Val (Val_Symbolic 13%Z) Mk_annot) Mk_annot) (Val (Val_Bits [BV{32%N} 0x14%Z]) Mk_annot) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0xfffffc3f%Z]) Mk_annot] Mk_annot; Binop ((Bvarith Bvshl)) (Unop (ZeroExtend 28%N) (Manyop Concat [Val (Val_Symbolic 6%Z) Mk_annot; Manyop Concat [Val (Val_Symbolic 3%Z) Mk_annot; Manyop Concat [Val (Val_Symbolic 12%Z) Mk_annot; Val (Val_Symbolic 10%Z) Mk_annot] Mk_annot] Mk_annot] Mk_annot) Mk_annot) (Val (Val_Bits [BV{32%N} 0x6%Z]) Mk_annot) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0xffffffef%Z]) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0x0%Z]) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0xfffffff3%Z]) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0x8%Z]) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0xfffffffe%Z]) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0x1%Z]) Mk_annot] Mk_annot)) Mk_annot;
    WriteReg "ESR_EL2" [] (RegVal_Base (Val_Bits [BV{32%N} 0x96000021%Z])) Mk_annot;
    WriteReg "FAR_EL2" [] (RegVal_Base (Val_Symbolic 186%Z)) Mk_annot;
    Smt (DeclareConst 220%Z (Ty_BitVec 40%N)) Mk_annot;
    Smt (DeclareConst 221%Z (Ty_BitVec 64%N)) Mk_annot;
    ReadReg "HPFAR_EL2" [] (RegVal_Base (Val_Symbolic 221%Z)) Mk_annot;
    Smt (DefineConst 222%Z (Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Val (Val_Symbolic 221%Z) Mk_annot; Val (Val_Bits [BV{64%N} 0xfffff0000000000f%Z]) Mk_annot] Mk_annot; Binop ((Bvarith Bvshl)) (Unop (ZeroExtend 24%N) (Val (Val_Symbolic 220%Z) Mk_annot) Mk_annot) (Val (Val_Bits [BV{64%N} 0x4%Z]) Mk_annot) Mk_annot] Mk_annot)) Mk_annot;
    WriteReg "HPFAR_EL2" [] (RegVal_Base (Val_Symbolic 222%Z)) Mk_annot;
    WriteReg "PSTATE" [Field "EL"] (RegVal_Struct [("EL", RegVal_Base (Val_Bits [BV{2%N} 0x2%Z]))]) Mk_annot;
    WriteReg "PSTATE" [Field "nRW"] (RegVal_Struct [("nRW", RegVal_Base (Val_Bits [BV{1%N} 0x0%Z]))]) Mk_annot;
    WriteReg "PSTATE" [Field "SP"] (RegVal_Struct [("SP", RegVal_Base (Val_Bits [BV{1%N} 0x1%Z]))]) Mk_annot;
    ReadReg "PSTATE" [Field "nRW"] (RegVal_Struct [("nRW", RegVal_Base (Val_Bits [BV{1%N} 0x0%Z]))]) Mk_annot;
    ReadReg "PSTATE" [Field "EL"] (RegVal_Struct [("EL", RegVal_Base (Val_Bits [BV{2%N} 0x2%Z]))]) Mk_annot;
    WriteReg "SPSR_EL2" [] (RegVal_Base (Val_Symbolic 213%Z)) Mk_annot;
    WriteReg "ELR_EL2" [] (RegVal_Base (Val_Symbolic 112%Z)) Mk_annot;
    WriteReg "PSTATE" [Field "SS"] (RegVal_Struct [("SS", RegVal_Base (Val_Bits [BV{1%N} 0x0%Z]))]) Mk_annot;
    WriteReg "PSTATE" [Field "D"] (RegVal_Struct [("D", RegVal_Base (Val_Bits [BV{1%N} 0x1%Z]))]) Mk_annot;
    WriteReg "PSTATE" [Field "A"] (RegVal_Struct [("A", RegVal_Base (Val_Bits [BV{1%N} 0x1%Z]))]) Mk_annot;
    WriteReg "PSTATE" [Field "I"] (RegVal_Struct [("I", RegVal_Base (Val_Bits [BV{1%N} 0x1%Z]))]) Mk_annot;
    WriteReg "PSTATE" [Field "F"] (RegVal_Struct [("F", RegVal_Base (Val_Bits [BV{1%N} 0x1%Z]))]) Mk_annot;
    WriteReg "PSTATE" [Field "IL"] (RegVal_Struct [("IL", RegVal_Base (Val_Bits [BV{1%N} 0x0%Z]))]) Mk_annot;
    ReadReg "HCR_EL2" [] (RegVal_Base (Val_Bits [BV{64%N} 0x0%Z])) Mk_annot;
    Barrier (RegVal_Base (Val_Enum ((Mk_enum_id 5%nat), Mk_enum_ctor 25%nat))) Mk_annot;
    ReadReg "VBAR_EL2" [] (RegVal_Base (Val_Bits [BV{64%N} 0x0%Z])) Mk_annot;
    BranchAddress (RegVal_Base (Val_Bits [BV{64%N} 0x200%Z])) Mk_annot;
    ReadReg "TCR_EL2" [] (RegVal_Base (Val_Bits [BV{64%N} 0x0%Z])) Mk_annot;
    WriteReg "_PC" [] (RegVal_Base (Val_Bits [BV{64%N} 0x200%Z])) Mk_annot
  ];
  [
    AssumeReg "VBAR_EL2" [] (RegVal_Base (Val_Bits [BV{64%N} 0x0%Z])) Mk_annot;
    AssumeReg "HCR_EL2" [] (RegVal_Base (Val_Bits [BV{64%N} 0x0%Z])) Mk_annot;
    AssumeReg "CFG_ID_AA64PFR0_EL1_EL3" [] (RegVal_Base (Val_Bits [BV{4%N} 0x1%Z])) Mk_annot;
    AssumeReg "CFG_ID_AA64PFR0_EL1_EL2" [] (RegVal_Base (Val_Bits [BV{4%N} 0x1%Z])) Mk_annot;
    AssumeReg "CFG_ID_AA64PFR0_EL1_EL1" [] (RegVal_Base (Val_Bits [BV{4%N} 0x1%Z])) Mk_annot;
    AssumeReg "CFG_ID_AA64PFR0_EL1_EL0" [] (RegVal_Base (Val_Bits [BV{4%N} 0x1%Z])) Mk_annot;
    AssumeReg "TCR_EL2" [] (RegVal_Base (Val_Bits [BV{64%N} 0x0%Z])) Mk_annot;
    Smt (DeclareConst 3%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 5%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 6%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 10%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 12%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 13%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 17%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 18%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 21%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 26%Z (Ty_BitVec 1%N)) Mk_annot;
    Smt (DeclareConst 27%Z (Ty_BitVec 1%N)) Mk_annot;
    AssumeReg "PSTATE" [Field "EL"] (RegVal_Base (Val_Bits [BV{2%N} 0x2%Z])) Mk_annot;
    AssumeReg "PSTATE" [Field "SP"] (RegVal_Base (Val_Bits [BV{1%N} 0x1%Z])) Mk_annot;
    AssumeReg "PSTATE" [Field "nRW"] (RegVal_Base (Val_Bits [BV{1%N} 0x0%Z])) Mk_annot;
    AssumeReg "SCR_EL3" [] (RegVal_Base (Val_Bits [BV{32%N} 0x401%Z])) Mk_annot;
    AssumeReg "SCTLR_EL2" [] (RegVal_Base (Val_Bits [BV{64%N} 0x4000002%Z])) Mk_annot;
    Assume (AExp_Binop (Eq) (AExp_Manyop (Bvmanyarith Bvand) [AExp_Val (AVal_Bits [BV{64%N} 0x77f8%Z]) Mk_annot; AExp_Val (AVal_Bits [BV{64%N} 0xfff0000000000007%Z]) Mk_annot] Mk_annot) (AExp_Val (AVal_Bits [BV{64%N} 0x0%Z]) Mk_annot) Mk_annot) Mk_annot;
    Smt (Assert (Binop (Eq) (Val (Val_Bits [BV{64%N} 0x0%Z]) Mk_annot) (Val (Val_Bits [BV{64%N} 0x0%Z]) Mk_annot) Mk_annot)) Mk_annot;
    Smt (DeclareConst 42%Z (Ty_BitVec 64%N)) Mk_annot;
    ReadReg "_PC" [] (RegVal_Base (Val_Symbolic 42%Z)) Mk_annot;
    Smt (DefineConst 43%Z (Manyop (Bvmanyarith Bvadd) [Val (Val_Symbolic 42%Z) Mk_annot; Val (Val_Bits [BV{64%N} 0x3d4%Z]) Mk_annot] Mk_annot)) Mk_annot;
    Smt (DefineConst 70%Z (Binop (Eq) (Val (Val_Symbolic 43%Z) Mk_annot) (Manyop (Bvmanyarith Bvand) [Val (Val_Symbolic 43%Z) Mk_annot; Val (Val_Bits [BV{64%N} 0xfffffffffffffff8%Z]) Mk_annot] Mk_annot) Mk_annot)) Mk_annot;
    ReadReg "PSTATE" [Field "EL"] (RegVal_Struct [("EL", RegVal_Base (Val_Bits [BV{2%N} 0x2%Z]))]) Mk_annot;
    ReadReg "SCTLR_EL2" [] (RegVal_Base (Val_Bits [BV{64%N} 0x4000002%Z])) Mk_annot;
    Smt (DefineConst 74%Z (Unop (Not) (Val (Val_Symbolic 70%Z) Mk_annot) Mk_annot)) Mk_annot;
    Branch 0%Z "model/aarch64.sail 13242:4 - 13245:5" Mk_annot;
    Smt (Assert (Unop (Not) (Val (Val_Symbolic 74%Z) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Unop (Not) (Val (Val_Symbolic 70%Z) Mk_annot) Mk_annot) Mk_annot)) Mk_annot;
    Smt (Assert (Binop (Eq) (Val (Val_Symbolic 43%Z) Mk_annot) (Manyop (Bvmanyarith Bvand) [Val (Val_Symbolic 43%Z) Mk_annot; Val (Val_Bits [BV{64%N} 0xfffffffffffffff8%Z]) Mk_annot] Mk_annot) Mk_annot)) Mk_annot;
    ReadReg "CFG_ID_AA64PFR0_EL1_EL2" [] (RegVal_Base (Val_Bits [BV{4%N} 0x1%Z])) Mk_annot;
    ReadReg "CFG_ID_AA64PFR0_EL1_EL3" [] (RegVal_Base (Val_Bits [BV{4%N} 0x1%Z])) Mk_annot;
    ReadReg "PSTATE" [Field "nRW"] (RegVal_Struct [("nRW", RegVal_Base (Val_Bits [BV{1%N} 0x0%Z]))]) Mk_annot;
    ReadReg "CFG_ID_AA64PFR0_EL1_EL0" [] (RegVal_Base (Val_Bits [BV{4%N} 0x1%Z])) Mk_annot;
    ReadReg "CFG_ID_AA64PFR0_EL1_EL1" [] (RegVal_Base (Val_Bits [BV{4%N} 0x1%Z])) Mk_annot;
    ReadReg "SCR_EL3" [] (RegVal_Base (Val_Bits [BV{32%N} 0x401%Z])) Mk_annot;
    ReadReg "HCR_EL2" [] (RegVal_Base (Val_Bits [BV{64%N} 0x0%Z])) Mk_annot;
    ReadReg "TCR_EL2" [] (RegVal_Base (Val_Bits [BV{64%N} 0x0%Z])) Mk_annot;
    Smt (DefineConst 910%Z (Unop (Not) (Binop (Eq) (Unop (Extract 63%N 52%N) (Val (Val_Symbolic 43%Z) Mk_annot) Mk_annot) (Val (Val_Bits [BV{12%N} 0x0%Z]) Mk_annot) Mk_annot) Mk_annot)) Mk_annot;
    Branch 1%Z "model/aarch_mem.sail 6443:4 - 6452:5" Mk_annot;
    Smt (Assert (Val (Val_Symbolic 910%Z) Mk_annot)) Mk_annot;
    Smt (Assert (Unop (Not) (Unop (Not) (Val (Val_Symbolic 70%Z) Mk_annot) Mk_annot) Mk_annot)) Mk_annot;
    Smt (DefineConst 1153%Z (Val (Val_Symbolic 42%Z) Mk_annot)) Mk_annot;
    Smt (DefineConst 1227%Z (Val (Val_Symbolic 43%Z) Mk_annot)) Mk_annot;
    ReadReg "PSTATE" [Field "SP"] (RegVal_Struct [("SP", RegVal_Base (Val_Bits [BV{1%N} 0x1%Z]))]) Mk_annot;
    ReadReg "PSTATE" [Field "N"] (RegVal_Struct [("N", RegVal_Base (Val_Symbolic 17%Z))]) Mk_annot;
    ReadReg "PSTATE" [Field "Z"] (RegVal_Struct [("Z", RegVal_Base (Val_Symbolic 27%Z))]) Mk_annot;
    ReadReg "PSTATE" [Field "C"] (RegVal_Struct [("C", RegVal_Base (Val_Symbolic 5%Z))]) Mk_annot;
    ReadReg "PSTATE" [Field "V"] (RegVal_Struct [("V", RegVal_Base (Val_Symbolic 26%Z))]) Mk_annot;
    ReadReg "PSTATE" [Field "PAN"] (RegVal_Struct [("PAN", RegVal_Base (Val_Symbolic 18%Z))]) Mk_annot;
    ReadReg "PSTATE" [Field "SS"] (RegVal_Struct [("SS", RegVal_Base (Val_Symbolic 21%Z))]) Mk_annot;
    ReadReg "PSTATE" [Field "IL"] (RegVal_Struct [("IL", RegVal_Base (Val_Symbolic 13%Z))]) Mk_annot;
    ReadReg "PSTATE" [Field "D"] (RegVal_Struct [("D", RegVal_Base (Val_Symbolic 6%Z))]) Mk_annot;
    ReadReg "PSTATE" [Field "A"] (RegVal_Struct [("A", RegVal_Base (Val_Symbolic 3%Z))]) Mk_annot;
    ReadReg "PSTATE" [Field "I"] (RegVal_Struct [("I", RegVal_Base (Val_Symbolic 12%Z))]) Mk_annot;
    ReadReg "PSTATE" [Field "F"] (RegVal_Struct [("F", RegVal_Base (Val_Symbolic 10%Z))]) Mk_annot;
    Smt (DefineConst 1254%Z (Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Manyop (Bvmanyarith Bvor) [Val (Val_Bits [BV{32%N} 0x0%Z]) Mk_annot; Binop ((Bvarith Bvshl)) (Unop (ZeroExtend 28%N) (Manyop Concat [Val (Val_Symbolic 17%Z) Mk_annot; Manyop Concat [Val (Val_Symbolic 27%Z) Mk_annot; Manyop Concat [Val (Val_Symbolic 5%Z) Mk_annot; Val (Val_Symbolic 26%Z) Mk_annot] Mk_annot] Mk_annot] Mk_annot) Mk_annot) (Val (Val_Bits [BV{32%N} 0x1c%Z]) Mk_annot) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0xffbfffff%Z]) Mk_annot] Mk_annot; Binop ((Bvarith Bvshl)) (Unop (ZeroExtend 31%N) (Val (Val_Symbolic 18%Z) Mk_annot) Mk_annot) (Val (Val_Bits [BV{32%N} 0x16%Z]) Mk_annot) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0xffdfffff%Z]) Mk_annot] Mk_annot; Binop ((Bvarith Bvshl)) (Unop (ZeroExtend 31%N) (Val (Val_Symbolic 21%Z) Mk_annot) Mk_annot) (Val (Val_Bits [BV{32%N} 0x15%Z]) Mk_annot) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0xffefffff%Z]) Mk_annot] Mk_annot; Binop ((Bvarith Bvshl)) (Unop (ZeroExtend 31%N) (Val (Val_Symbolic 13%Z) Mk_annot) Mk_annot) (Val (Val_Bits [BV{32%N} 0x14%Z]) Mk_annot) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0xfffffc3f%Z]) Mk_annot] Mk_annot; Binop ((Bvarith Bvshl)) (Unop (ZeroExtend 28%N) (Manyop Concat [Val (Val_Symbolic 6%Z) Mk_annot; Manyop Concat [Val (Val_Symbolic 3%Z) Mk_annot; Manyop Concat [Val (Val_Symbolic 12%Z) Mk_annot; Val (Val_Symbolic 10%Z) Mk_annot] Mk_annot] Mk_annot] Mk_annot) Mk_annot) (Val (Val_Bits [BV{32%N} 0x6%Z]) Mk_annot) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0xffffffef%Z]) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0x0%Z]) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0xfffffff3%Z]) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0x8%Z]) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0xfffffffe%Z]) Mk_annot] Mk_annot; Val (Val_Bits [BV{32%N} 0x1%Z]) Mk_annot] Mk_annot)) Mk_annot;
    WriteReg "ESR_EL2" [] (RegVal_Base (Val_Bits [BV{32%N} 0x96000000%Z])) Mk_annot;
    WriteReg "FAR_EL2" [] (RegVal_Base (Val_Symbolic 1227%Z)) Mk_annot;
    Smt (DeclareConst 1261%Z (Ty_BitVec 40%N)) Mk_annot;
    Smt (DeclareConst 1262%Z (Ty_BitVec 64%N)) Mk_annot;
    ReadReg "HPFAR_EL2" [] (RegVal_Base (Val_Symbolic 1262%Z)) Mk_annot;
    Smt (DefineConst 1263%Z (Manyop (Bvmanyarith Bvor) [Manyop (Bvmanyarith Bvand) [Val (Val_Symbolic 1262%Z) Mk_annot; Val (Val_Bits [BV{64%N} 0xfffff0000000000f%Z]) Mk_annot] Mk_annot; Binop ((Bvarith Bvshl)) (Unop (ZeroExtend 24%N) (Val (Val_Symbolic 1261%Z) Mk_annot) Mk_annot) (Val (Val_Bits [BV{64%N} 0x4%Z]) Mk_annot) Mk_annot] Mk_annot)) Mk_annot;
    WriteReg "HPFAR_EL2" [] (RegVal_Base (Val_Symbolic 1263%Z)) Mk_annot;
    WriteReg "PSTATE" [Field "EL"] (RegVal_Struct [("EL", RegVal_Base (Val_Bits [BV{2%N} 0x2%Z]))]) Mk_annot;
    WriteReg "PSTATE" [Field "nRW"] (RegVal_Struct [("nRW", RegVal_Base (Val_Bits [BV{1%N} 0x0%Z]))]) Mk_annot;
    WriteReg "PSTATE" [Field "SP"] (RegVal_Struct [("SP", RegVal_Base (Val_Bits [BV{1%N} 0x1%Z]))]) Mk_annot;
    ReadReg "PSTATE" [Field "nRW"] (RegVal_Struct [("nRW", RegVal_Base (Val_Bits [BV{1%N} 0x0%Z]))]) Mk_annot;
    ReadReg "PSTATE" [Field "EL"] (RegVal_Struct [("EL", RegVal_Base (Val_Bits [BV{2%N} 0x2%Z]))]) Mk_annot;
    WriteReg "SPSR_EL2" [] (RegVal_Base (Val_Symbolic 1254%Z)) Mk_annot;
    WriteReg "ELR_EL2" [] (RegVal_Base (Val_Symbolic 1153%Z)) Mk_annot;
    WriteReg "PSTATE" [Field "SS"] (RegVal_Struct [("SS", RegVal_Base (Val_Bits [BV{1%N} 0x0%Z]))]) Mk_annot;
    WriteReg "PSTATE" [Field "D"] (RegVal_Struct [("D", RegVal_Base (Val_Bits [BV{1%N} 0x1%Z]))]) Mk_annot;
    WriteReg "PSTATE" [Field "A"] (RegVal_Struct [("A", RegVal_Base (Val_Bits [BV{1%N} 0x1%Z]))]) Mk_annot;
    WriteReg "PSTATE" [Field "I"] (RegVal_Struct [("I", RegVal_Base (Val_Bits [BV{1%N} 0x1%Z]))]) Mk_annot;
    WriteReg "PSTATE" [Field "F"] (RegVal_Struct [("F", RegVal_Base (Val_Bits [BV{1%N} 0x1%Z]))]) Mk_annot;
    WriteReg "PSTATE" [Field "IL"] (RegVal_Struct [("IL", RegVal_Base (Val_Bits [BV{1%N} 0x0%Z]))]) Mk_annot;
    Barrier (RegVal_Base (Val_Enum ((Mk_enum_id 7%nat), Mk_enum_ctor 25%nat))) Mk_annot;
    ReadReg "VBAR_EL2" [] (RegVal_Base (Val_Bits [BV{64%N} 0x0%Z])) Mk_annot;
    BranchAddress (RegVal_Base (Val_Bits [BV{64%N} 0x200%Z])) Mk_annot;
    WriteReg "_PC" [] (RegVal_Base (Val_Bits [BV{64%N} 0x200%Z])) Mk_annot
  ]
].
